### ISSUE TITLE
Go through specification of Dockerfile and re-read all instructions with reproducibility in mind

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#3]

**Comment by psychemedia** [comment]
Would it also make sense to provide, as supporting material at least, a recipe for running docker instances locally and in the cloud?

Running docker on Digital Ocean is quite straightforward ([example](https://github.com/ouseful-course-containers/ou-tm129-robotlab/wiki#using-docker-on-a-remote-host)?

I'm not sure if there are even simpler hosted docker environments, suitable for occasional, personal use and/or free testing, out there? It's been some time since I looked around for them. Here are a couple I found previously (Simon Willison's `datasette publish` is a good crib for these):

- [Heroku](https://devcenter.heroku.com/articles/container-registry-and-runtime)
- *Zeit now* ([example](https://dev.to/grikomsn/how-i-deployed-a-dockerized-nodejs-app-on-zeit-now-358b)) (though IIRC, build size is limited?)

**Comment by nuest** [comment]
I think the aspect of "where is this image running" could be considered in the rules. _What would be contents that a Dockerfile needs so that the image works on Digital Ocean?_

OTOH, I am unsure about adding a single `docker run ...` example, because that might quickly turn into a "Ten simple rules for using Docker ..", and not Docker-_files_.

Maybe the building and running of the `Dockerfile` could be part of a "box" ?

**Comment by psychemedia** [comment]
Agreed re: not going off on a tangent. By the by, another run option may be to use Binder, though that might also require tweaking of the Dockerfile ([docs](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html)).
