### ISSUE TITLE
Multiple images vs. one image with entrypoints/cmds

### ISSUE THREAD

**Issue by nuest** [nuest/ten-simple-rules-dockerfiles#52]
In the current text I made the suggestion to use the same container for both development and 

https://figshare.com/articles/Using_Docker_to_Support_Reproducible_Research/1101910 suggest something different, namely a base + dev + release images, the latter to only run the workflow and second to have a UI (like Jupyter) with a common environment (base).

![image](https://user-images.githubusercontent.com/1325054/72609426-2412b380-3925-11ea-9936-fc47466724b6.png)

_I still think a multiple-image set-up is quite error prone, but it work better for some users?_

**Comment by psychemedia** [comment]
I mentioned something related somewhere in the context of multistage builds; sometimes you have build step dependencies that you have no need for in the final container. They thus add weight and clutter to the actual final *functional* container. A principle of parsimony would suggest not including such buildstep dependences in the functional container.

**Comment by vsoch** [comment]
This setup (base, development, release) is more well suited to software development - releases can be assured to be relatively stable, dev images (or sometimes called nightly) go out frequently (typically with whatever is the content of the living master branch) and then base images are useful to build the release for multistage builds. This is a different set of needs than data science containers, which err on the side of being larger because you wouldn't want a multi stage build to nix out source code that might be needed for reproducibility in the future. The different levels of containers also (sort of) imply a more complex setup that would warrant more people to work on it, something less likely for data science.

So - I would bet that you might see this kind of setup for some data science containers for which the developers have experience with software development, but to promote it as a best practice globally for data science doesn't make a ton of sense (in my opinion).

**Comment by vsoch** [comment]
If the data scientist needs multiple entry points (that could be afforded by multiple containers) he/she could use something like the Scientific Filesystem (https://sci-f.github.io/)

**Comment by nuest** [comment]
I agree with @vsoch this goes beyond the scope of what we can explain well, and what makes sense for the audience (although we include _a lot_ of things that might go beyond the grasp of the audience... will have to iterate for that).
