### ISSUE TITLE
Add note about audience for paper to introduction

### ISSUE THREAD

**Issue by vsoch** [nuest/ten-simple-rules-dockerfiles#55]
After the rounds of edits are finished and the paper is in some ready state, I would like to give one more read through, and also take a shot at adding a section to the beginning that clearly defines the audience for the paper - likely focused on single application containers for data scientists.

**Comment by nuest** [comment]
So would I! With the hiatus over January/February, it should be possible to "kill some darlings", because shortening is really needed and I'm more and more convinced we need to through out content.

@vsoch What do you think - would you do the "audience" first and then see what does not fit that audience, what goes to far? Or should we have a call to close the open issues and just go through each rule and see how we can reduce it to the gist?

**Comment by vsoch** [comment]
I’d be good with going through and doing another PR to chop out some things - given the number of authors I think that asynchronous communication/review will be much more efficient than having a call.

**Comment by nuest** [comment]
@vsoch This is not closed yet, but I think the content is there - it just needs "sharpening" and probably the scope is a bit repetetive (and too long).

**Comment by vsoch** [comment]
So do you want me to take a look now (or wait a bit longer?)

**Comment by vsoch** [comment]
See #57

**Comment by nuest** [comment]
The audience and scope is much better described now, albeit quite long.
